export const UPDATE_FIRSTINPUT = 'UPDATE_FIRSTINPUT';
export const UPDATE_SECONDINPUT = 'UPDATE_SECONDINPUT';
export const UPDATE_FIRSTCURRENCY = 'UPDATE_FIRSTCURRENCY';
export const UPDATE_SECONDCURRENCY = 'UPDATE_SECONDCURRENCY';
export const CONVERT_FIRSTINPUT = 'CONVERT_FIRSTINPUT';
export const CONVERT_SECONDINPUT = 'CONVERT_SECONDINPUT';